name: NER
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: NER_RUN
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Your ML workflow goes here
          echo "## NER CREATED SAMPLE" > report.md
          cml-publish NER-BEPROJECT/image.png --md >> report.md
          cml-send-comment report.md
